template: true 
valuesFilePath: ./values.yml

resources:
  - name: propertyBag_1
    type: PropertyBag
    configuration:
      runNumber: 0
 
  - name: propertyBag_2
    type: PropertyBag
    configuration:
      runNumber: 0

pipelines:
  - name: A_parent
    steps: 
      - name: A_test
        type: Bash
        configuration:
          inputResources:
            - name: propertyBag_1
          outputResources:
            - name: propertyBag_2
        execution:
          onExecute:
            - write_output propertyBag_2 runNumber=${run_number}
 
  - name: A_waitOnParent
    configuration:
      dependencyMode:
        waitOnParentComplete: true
        waitOnParentSuccess: true
    steps: 
      - name: B_test
        type: Bash
        configuration:
          inputResources:
            - name: propertyBag_2
        execution:
          onExecute:
            - echo "test"