template: true 
valuesFilePath: ./values.yml

resources:
  - name: myFirstRepo
    type: GitRepo
    configuration:
      gitProvider: {{ .Values.myRepo.gitProvider }}
      path: {{ .Values.myRepo.path }}
  - name: propertyBag
    type: PropertyBag
    configuration:
      foo: bar
      foo1: bar1
      foo2: bar2
  - name: artifactory_product_release_cron
    type: CronTrigger
    configuration:
      interval: '*/5 * * * *'
      branches:
        include: ^preRelease/jfrtp-.+$|master

pipelines:
  - name: pipeline_scheduled_triggers
    steps:
      - name: step_1
        type: Bash
        configuration:
          inputResources:
            - name: artifactory_product_release_cron
        execution:
          onExecute:
            - printenv
  - name: pipeline_scheduled_triggers2
    steps:
      - name: step_2
        type: Bash
        configuration:
          inputResources:
            - name: artifactory_product_release_cron
        execution:
          onExecute:
            - printenv
